import { OpalTheme } from './types';

export const OPAL_THEMES: OpalTheme[] = [
  {
    id: 'black-opal',
    name: 'Australian Black Opal',
    description: 'Deep, dark body tone with electric flashes of green and blue.',
    baseColor: '#0a0a10',
    colors: ['#00ff88', '#0099ff', '#3300aa'],
    roughness: 0.2,
    metalness: 0.8,
    bgGradient: ['#000000', '#111122'],
    particleColor: '#00ffff',
    speedModifier: 1.0,
  },
  {
    id: 'welo-opal',
    name: 'Ethiopian Welo',
    description: 'Translucent white base with a honeycomb of neon rainbow fire.',
    baseColor: '#fff5e6',
    colors: ['#ff0055', '#ffff00', '#00ffaa'],
    roughness: 0.1,
    metalness: 0.6,
    bgGradient: ['#2b1a1a', '#443333'],
    particleColor: '#ffaa00',
    speedModifier: 0.8,
  },
  {
    id: 'fire-opal',
    name: 'Mexican Fire Opal',
    description: 'Vibrant cherry, sun-orange, and gold tones resembling trapped magma.',
    baseColor: '#4a1000',
    colors: ['#ff4400', '#ffaa00', '#ffff88'],
    roughness: 0.3,
    metalness: 0.5,
    bgGradient: ['#220500', '#441000'],
    particleColor: '#ffff00',
    speedModifier: 1.2,
  },
  {
    id: 'boulder-opal',
    name: 'Boulder Opal',
    description: 'Ironstone matrix veins splitting brilliant turquoise and violet seams.',
    baseColor: '#3b2f2f',
    colors: ['#00ffff', '#aa00ff', '#0000ff'],
    roughness: 0.6,
    metalness: 0.4,
    bgGradient: ['#1a100a', '#2d2015'],
    particleColor: '#00aaff',
    speedModifier: 0.9,
  },
  {
    id: 'coober-pedy',
    name: 'Coober Pedy Crystal',
    description: 'Milky, pale, and dreamy with soft pastel flashes.',
    baseColor: '#e0f0ff',
    colors: ['#aaccff', '#ffccff', '#ccffcc'],
    roughness: 0.1,
    metalness: 0.9,
    bgGradient: ['#0a1020', '#102040'],
    particleColor: '#ffffff',
    speedModifier: 0.7,
  },
  {
    id: 'nebula-opal',
    name: 'Cosmic Nebula',
    description: 'An otherworldly synthetic opal forged in the heart of a dying star.',
    baseColor: '#100020',
    colors: ['#ff00ff', '#00ffff', '#ffff00'],
    roughness: 0.0,
    metalness: 1.0,
    bgGradient: ['#000000', '#220033'],
    particleColor: '#ff00ff',
    speedModifier: 1.5,
  }
];